apiVersion: v1
kind: ConfigMap
metadata:
 name: zurisaddairj-config
 labels:
   app: postgres
data:
 DEV_SECRET_KEY: {DEV_SECRET_KEY}
 DEV_DATABASE: {DEV_DATABASE}
 DEV_USER: {DEV_USER}
 DEV_PASSWORD: {DEV_PASSWORD}
 DEV_HOST: {DEV_HOST}
 DEV_PORT: {DEV_PORT}
 
 PROD_SECRET_KEY: Saddai.1411
 PROD_DATABASE: lsycaygn
 PROD_USER: lsycaygn
 PROD_PASSWORD: zgCFqMOxGWm1NRyzDOURIaTmgwDt22Vw
 PROD_HOST: mahmud.db.elephantsql.com 
 PROD_PORT: "5432"
