apiVersion: v1
kind: ConfigMap
metadata:
 name: zurisaddairj-config
 labels:
   app: postgres
data:
 DEV_SECRET_KEY: MY_DEV_SECRET_KEY
 DEV_DATABASE: MY_DEV_DATABASE
 DEV_USER: MY_DEV_USER
 DEV_PASSWORD: MY_DEV_PASSWORD
 DEV_HOST: MY_DEV_HOST
 DEV_PORT: MY_DEV_PORT
 
 PROD_SECRET_KEY: Saddai.1411
 PROD_DATABASE: lsycaygn
 PROD_USER: lsycaygn
 PROD_PASSWORD: zgCFqMOxGWm1NRyzDOURIaTmgwDt22Vw
 PROD_HOST: mahmud.db.elephantsql.com 
 PROD_PORT: "5432"
