apiVersion: v1
kind: ConfigMap
metadata:
 name: zurisaddairj-config
 labels:
   app: postgres
data:
 DEV_SECRET_KEY: Saddai.1411
 DEV_DATABASE: lsycaygn
 DEV_USER: lsycaygn
 DEV_PASSWORD: zgCFqMOxGWm1NRyzDOURIaTmgwDt22Vw
 DEV_HOST: mahmud.db.elephantsql.com
 DEV_PORT: "5432"
 
 PROD_SECRET_KEY: Saddai.1411
 PROD_DATABASE: lsycaygn
 PROD_USER: lsycaygn
 PROD_PASSWORD: zgCFqMOxGWm1NRyzDOURIaTmgwDt22Vw
 PROD_HOST: mahmud.db.elephantsql.com 
 PROD_PORT: "5432"
