# Generated by Django 3.1.3 on 2023-02-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(default='')),
                ('autor', models.TextField(default='')),
                ('genero', models.TextField(default='')),
                ('editorial', models.TextField(default='')),
                ('anio', models.IntegerField(default='yyyy')),
                ('num_pages', models.IntegerField(default=0)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('categoria', models.TextField(default=' ')),
                ('edicion', models.IntegerField(default=0)),
                ('idioma', models.TextField(default=' ')),
            ],
        ),
    ]
