# Generated by Django 3.1.3 on 2023-05-26 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='libros.libro'),
        ),
    ]
